# Generated by Django 6.0.5 on 2026-05-10 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(default='NG', max_length=5)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('momo_network', models.CharField(blank=True, max_length=100, null=True)),
                ('eft_bank', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('business_id', models.CharField(max_length=120)),
                ('transfer_type', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notification_url', models.URLField(blank=True, null=True)),
                ('momo_network', models.CharField(blank=True, max_length=100, null=True)),
                ('csv_file', models.FileField(upload_to='bulk_transfers/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('bvn', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_id', models.CharField(max_length=120, unique=True)),
                ('business_id', models.CharField(max_length=120)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lien_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('aggregator_wallet', models.BooleanField(default=False)),
                ('payout_allowed', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('bulk_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.bulktransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(default='NG', max_length=2)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('onus_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('tx_type', models.CharField(choices=[('payin', 'Payin'), ('payout', 'Payout')], max_length=20)),
                ('channel', models.CharField(choices=[('dynamic_virtual_account', 'Dynamic Virtual Account'), ('fixed_virtual_account', 'Fixed Virtual Account'), ('wallet_link', 'Wallet Link'), ('mobile_money_collection', 'Mobile Money Collection'), ('bank_transfer', 'Bank Transfer'), ('mobile_money_payout', 'Mobile Money Payout'), ('eft_payout', 'EFT Payout'), ('wallet_transfer', 'Wallet Transfer'), ('bulk_transfer', 'Bulk Transfer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('country_code', models.CharField(default='NG', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_type', models.CharField(choices=[('WALLET_TO_BANK_ACCOUNT', 'Wallet to Bank'), ('WALLET_TO_WALLET', 'Wallet to Wallet'), ('WALLET_TO_MOMO', 'Wallet to MoMo'), ('WALLET_TO_EFT', 'Wallet to EFT')], max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(default='PENDING', max_length=50)),
                ('notification_url', models.URLField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.beneficiary')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='api.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=30)),
                ('otp_required', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('initiating_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='PROCESSING', max_length=50)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money', to='api.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('dynamic', 'Dynamic'), ('fixed', 'Fixed'), ('wallet', 'Wallet')], max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('completion_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='api.customer')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_account', to='api.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('onus_reference', models.CharField(max_length=120)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reversal', models.BooleanField(default=False)),
                ('fee', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
