# Generated by Django 6.0.5 on 2026-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='onus_reference',
            field=models.CharField(default='ONUS-NUB-3766142206473-11052026-143720', max_length=255),
            preserve_default=False,
        ),
    ]
