# Generated by Django 6.0.5 on 2026-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_virtualaccount_onus_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='completion_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
