# Generated by Django 6.0.5 on 2026-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_virtualaccount_completion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
