# Generated by Django 6.0.5 on 2026-05-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payout_provider_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='onus_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='processing_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
