from django.urls import path

from .views import (
    BankListView,
    BankTransferView,
    BulkTransferView,
    CreateDynamicVirtualAccountView,
    CreateFixedVirtualAccountView,
    EFTPayoutView,
    FixedVirtualAccountListView,
    FundSandboxWalletView,
    MobileMoneyCollectionView,
    MobileMoneyNetworksView,
    MobileMoneyPayoutView,
    NameEnquiryView,
    PayinPaymentRequestListView,
    PayonusWebhookView,
    TransferRequestListView,
    VerifyMobileMoneyOTPView,
    VerifySinglePaymentView,
    WalletListView,
    WalletTransactionListView,
    WalletTransferView,
    WebhookLogListView,
)

urlpatterns = [
    path(
        "payments/dynamic-account/",
        CreateDynamicVirtualAccountView.as_view(),
        name="dynamic-account",
    ),
    path(
        "payments/fixed-account/",
        CreateFixedVirtualAccountView.as_view(),
        name="fixed-account",
    ),
    path(
        "webhooks/payonus/",
        PayonusWebhookView.as_view(),
        name="payonus-webhook",
    ),
    path(
        "payments/fixed-accounts/",
        FixedVirtualAccountListView.as_view(),
    ),
    path(
        "payments/mobile-money/",
        MobileMoneyCollectionView.as_view(),
    ),
    path(
        "payments/mobile-money/verify-otp/",
        VerifyMobileMoneyOTPView.as_view(),
    ),
    path(
        "payments/mobile-money/networks/",
        MobileMoneyNetworksView.as_view(),
    ),
    path(
        "payouts/banks/",
        BankListView.as_view(),
    ),
    path(
        "payouts/name-enquiry/",
        NameEnquiryView.as_view(),
    ),
    path(
        "payouts/bank-transfer/",
        BankTransferView.as_view(),
    ),
    path(
        "payouts/fund-wallet/",
        FundSandboxWalletView.as_view(),
    ),
    path(
        "payouts/transfers/",
        TransferRequestListView.as_view(),
    ),
    path(
        "payouts/mobile-money/",
        MobileMoneyPayoutView.as_view(),
    ),
    path(
        "payouts/eft/",
        EFTPayoutView.as_view(),
    ),
    path(
        "wallets/",
        WalletListView.as_view(),
    ),
    path(
        "wallets/transfer/",
        WalletTransferView.as_view(),
    ),
    path(
        "wallets/transactions/",
        WalletTransactionListView.as_view(),
    ),
    path(
        "payments/verify/",
        VerifySinglePaymentView.as_view(),
    ),
    path(
        "payouts/bulk-transfer/",
        BulkTransferView.as_view(),
    ),
    path(
        "payments/requests/",
        PayinPaymentRequestListView.as_view(),
    ),
    path(
        "webhooks/logs/",
        WebhookLogListView.as_view(),
    ),
]
