from django.urls import path

from .views import (
    BankListView,
    BankTransferView,
    CreateDynamicVirtualAccountView,
    CreateFixedVirtualAccountView,
    FixedVirtualAccountListView,
    MobileMoneyCollectionView,
    MobileMoneyNetworksView,
    NameEnquiryView,
    PayonusWebhookView,
    VerifyMobileMoneyOTPView,
)

urlpatterns = [
    path(
        "payments/dynamic-account/",
        CreateDynamicVirtualAccountView.as_view(),
        name="dynamic-account",
    ),
    path(
        "payments/fixed-account/",
        CreateFixedVirtualAccountView.as_view(),
        name="fixed-account",
    ),
    path(
        "webhooks/payonus/",
        PayonusWebhookView.as_view(),
        name="payonus-webhook",
    ),
    path(
        "payments/fixed-accounts/",
        FixedVirtualAccountListView.as_view(),
    ),
    path(
        "payments/mobile-money/",
        MobileMoneyCollectionView.as_view(),
    ),
    path(
        "payments/mobile-money/verify-otp/",
        VerifyMobileMoneyOTPView.as_view(),
    ),
    path(
        "payments/mobile-money/networks/",
        MobileMoneyNetworksView.as_view(),
    ),
    path(
        "payouts/banks/",
        BankListView.as_view(),
    ),
    path(
        "payouts/name-enquiry/",
        NameEnquiryView.as_view(),
    ),
    path(
        "payouts/bank-transfer/",
        BankTransferView.as_view(),
    ),
]
